Renaming API_Version and project Parameter.
* Google doesn't support v1beta1/2 anymore.
* 'projectId' parameter is no longer supported, new parameter is 'project'

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "turnedDown",
    "message": "Version v1beta2 of this API is no longer available. Please try again using JSON API v1. To request temporary reinstatement for your project, please visit https://docs.google.com/forms/d/1isIxBZg3rsQbDN_TOalZaz1WT_ebJchsrlv-Qr_r9mY/viewform?entry.244568692=38914250655&entry.176324201=v1beta2&entry.1071661541-Qr_r9mY/prefill",
    "extendedHelp": "https://cloud.google.com/storage/docs/json_api/v1/how-tos/migrate"
   }
  ],
  "code": 400,
  "message": "Version v1beta2 of this API is no longer available. Please try again using JSON API v1. To request temporary reinstatement for your project, please visit https://docs.google.com/forms/d/1isIxBZg3rsQbDN_TOalZaz1WT_ebJchsrlv-Qr_r9mY/viewform?entry.244568692=38914250655&entry.176324201=v1beta2&entry.1071661541-Qr_r9mY/prefill"
 }
}

ArgumentError: Missing required parameters: project.
from /Users/adihochmann/work/lab/ruby/2.1.0/gems/google-api-client-0.8.2/lib/google/api_client/discovery/method.rb:311:in `validate_parameters'